### ISSUE TITLE
Similar issue to other people as Mario Kart 8 file is showing 3 folders: Code, Content, Meta.

### ISSUE THREAD

**Issue by Dawud04** [RedDuckss/CemUI#103]
This is my first time trying out this emulator.
After looking at tutorials of people managing to download the games and running them as WUD or WUX files.
I download the 8 rar files which are in 8 parts of the game.
After extracting these, I get to the point of it showing those three folders. How can I get CEMU to recognize the file?

**Comment by RedDuckss** [comment]
This is _CemUI_, not Cemu. CemUI is not an emulator, it is a _frontend_ for Cemu. We do not offer support for Cemu-specific issues. Please ask for support in the proper place, like that Cemu forums or the Cemu Discord server.
