### ISSUE TITLE
Does not follow directory junctions

### ISSUE THREAD

**Issue by Corecii** [RedDuckss/CemUI#44]
I have my games folder set up where most games are in the folder directly, but Breath of the Wild is on a separate, faster drive, connected to the games folder using a directory junction (`mklink /J link target` in command prompt on Windows). CemUI doesn't show Breath of the Wild in my library, despite the directory junction being in the games folder. I can navigate through the directory to launch Breath of the Wild fine in Cemu, and the junction generally acts just like a folder.

Games folder:
![image](https://user-images.githubusercontent.com/1669436/30237590-07ecd4fe-94fb-11e7-9373-56c822b9af8e.png)

Library:
![image](https://user-images.githubusercontent.com/1669436/30237564-6ea298ec-94fa-11e7-999c-94aa5fdcd909.png)

Junction acting like a folder:
![image](https://user-images.githubusercontent.com/1669436/30237593-1769b42e-94fb-11e7-81f6-8dec04359d29.png)

**Comment by RedDuckss** [comment]
I wasn't aware of the existence of directory junctions. I will look into this, thank you.

**Comment by RedDuckss** [comment]
Fixed in latest push. An updated build has not been published yet, however you can run from source for now (a new build should be out soon)

**Comment by Corecii** [comment]
Looks like that fixed it, thanks!
