### ISSUE TITLE
Unplayable games are recommended.

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [RedDuckss/CemUI#46]
I think it's better to only recommend games with good compatibility? ;)

**Comment by RedDuckss** [comment]
The issue with this suggestion is that not all games have compatibility data, meaning the number of results would be very low. This also means that games that have high compatibility but no compatibility data won't be displayed.

**Comment by RedDuckss** [comment]
Updated the API to exclude games with a compatibility of `Loads: Game loads, but crashes in title screen/menu/in-game.` or `Unplayable: Crashes when booting/infinite black screen.`. Issue should be fixed.

**Comment by TheStruggleForAntiSpaghetti** [comment]
Where do you get your compatibility data?

**Comment by RedDuckss** [comment]
I scraped it from http://compat.cemu.info/

**Comment by TheStruggleForAntiSpaghetti** [comment]
Maybe only recommend the ones from "http://compat.cemu.info/?rating=4&sort=All" & "http://compat.cemu.info/?rating=5&sort=All" and not in users library?
