### ISSUE TITLE
Some Games Not Showing Up Despite Similar Folder Structure

### ISSUE THREAD

**Issue by jddg5wa** [RedDuckss/CemUI#53]
Not too much information I can give but will do my best. I set the game folder and some games have not shown up in cemu. I have multiple games following the same structure yet a few may not show up while the others will. 

This also includes all virtual console games but they don't have a meta folder. Could that be an issue?

The standard structure I am refering for the games that do and do not show up. 
RomFolder
├── code
|   ├── // Code files
|   └── game.rpx
├── content
|   └── // Content files
└── meta
|   ├── // Meta files
|   └── meta.xml

Some of the games that aren't showing up, aside from any VC game, is Pikmin 3, Mario Tennis Ultra Smash, Game & Wario, and Wii Sports Club. From my checking they all follow the standard folder structure. 

The only steps to reproduce, that I know, are to have the games in game folder, set CemUI to game folder. 

I don't know if it matters but this happened on the non-release version and then I used the release version moments after, since I hadn't known it existed, and it still happened. I had cleared all files to make sure the release version of CemUI would let me repick the games folder.

**Comment by RedDuckss** [comment]
> This also includes all virtual console games but they don't have a meta folder. Could that be an issue?

Yes, this is an issue. Without the meta folder CemUI cannot identify an RPX rom, as it uses files found in the meta folder. However, I may or may not know a solution to this. Would you mind sending a screenshot of the `code` folder for one, or more, of your VC games?

> Some of the games that aren't showing up, aside from any VC game, is Pikmin 3, Mario Tennis Ultra Smash, Game & Wario, and Wii Sports Club. From my checking they all follow the standard folder structure.

This sounds like the games title IDs are not stored in the database I use for the custom API. If you wouldnt mind, please zip the `meta` folder (and ONLY the `meta` folder) of each of the affected games and send that as well. That way I can check the contents and compare the games title ID to the database, and see if they are there.

**Comment by jddg5wa** [comment]
That's great, the regular games show up now. Nice work and I hadn't even gotten back to you yet. Cool! The VC games still don't seem to show up though. I haven't tested it yet but supposedly there is a method to create a Meta folder that I will test and see if that lets them show up. For now I've added the image of the code folders you asked. 

![wiiu vc code folders](https://user-images.githubusercontent.com/2061754/30255774-cdbea1d4-965a-11e7-8f60-ac9be61e1102.png)

**Comment by jddg5wa** [comment]
By the way, this is the contents of the App file. Looks like it contains a bunch of the identifying information. 

![f04eadeba73a2babe48177bcbaf08944](https://user-images.githubusercontent.com/2061754/30255830-22c76526-965b-11e7-93ed-e863dc4c6454.png)

**Comment by RedDuckss** [comment]
Welp there goes that idea. I asked for screenshots of your `code` folder because there's a file there (`app.xml`) which is very similar to one of the files in the meta folder that CemUI uses. I was going to use that file as a fallback, but your first screenshot doesn't have an `app.xml`, so that won't work here...

**Comment by RedDuckss** [comment]
I just checked the content of the rpx file itself to see if that contained anything useful (for wud and wux games we extract the product code from the rom itself, thought maybe I could do that with an rpx too). Nothing helpful. Seems like the only way to identify an rpx rom is either the meta folder or app.xml, but your first screenshot is a game that has neither...

**Comment by jddg5wa** [comment]
Hmm, Cemu doesn't log the correct title either. Seems more like a problem on my side since the other two have the expected files.

**Comment by RedDuckss** [comment]
Try to re-"dump" that rom (I have to say "dump" because legalness). It may have "dumped" incorrectly. Or maybe "dump" it from a different source.

**Comment by RedDuckss** [comment]
Reopening issue, forgot to do that before. Also bump.

**Comment by RedDuckss** [comment]
Closing this issue for now since I added the proper fallbacks to support valid VC rom structures. If the fix didn't work feel free to let me know and I'll reopen

**Comment by jakerdox** [comment]
I have a similar problem. I can run the game in CEMU but I can't make a path for it. The difference is that I have an xml folder. In my code folder I have a single rpx folder named Zelda and my meta folder looks like this.
![capture](https://user-images.githubusercontent.com/24424867/47405770-00ec5a80-d708-11e8-98c6-0ec7c78f5fc6.PNG)

**Comment by AntoninCamus** [comment]
I got too the issue with Twilight Princess HD which had only this in its `meta`folder : 
![Capture](https://user-images.githubusercontent.com/9219052/60466489-15e49a80-9c54-11e9-9b70-4f2ebc4975df.PNG)

[meta.zip](https://github.com/RedDuckss/CemUI/files/3347310/meta.zip)

**Comment by Markyza** [comment]
> I got too the issue with Twilight Princess HD which had only this in its `meta`folder :
> ![Capture](https://user-images.githubusercontent.com/9219052/60466489-15e49a80-9c54-11e9-9b70-4f2ebc4975df.PNG)
> 
> [meta.zip](https://github.com/RedDuckss/CemUI/files/3347310/meta.zip)

Maybe it's late, but your 'meta' and 'content' folders have not all files. You have two options:
1. You can download EUR version of Twilight Princess HD  'meta' and 'content' folders with Wii U USB Helper and add to your own folders rest of files.
2. You can use attached archive.

With best regards.


[Zelda.zip](https://github.com/RedDuckss/CemUI/files/4201315/Zelda.zip)

**Comment by schanze1** [comment]
> > I got too the issue with Twilight Princess HD which had only this in its `meta`folder :
> > ![Capture](https://user-images.githubusercontent.com/9219052/60466489-15e49a80-9c54-11e9-9b70-4f2ebc4975df.PNG)
> > [meta.zip](https://github.com/RedDuckss/CemUI/files/3347310/meta.zip)
> 
> Maybe it's late, but your 'meta' and 'content' folders have not all files. You have two options:
> 
> 1. You can download EUR version of Twilight Princess HD  'meta' and 'content' folders with Wii U USB Helper and add to your own folders rest of files.
> 2. You can use attached archive.
> 
> With best regards.
> 
> [Zelda.zip](https://github.com/RedDuckss/CemUI/files/4201315/Zelda.zip)

AWESOME...Thank you for the files. Everything working fine now

**Comment by dictory99** [comment]
> > I got too the issue with Twilight Princess HD which had only this in its `meta`folder :
> > ![Capture](https://user-images.githubusercontent.com/9219052/60466489-15e49a80-9c54-11e9-9b70-4f2ebc4975df.PNG)
> > [meta.zip](https://github.com/RedDuckss/CemUI/files/3347310/meta.zip)
> 
> Maybe it's late, but your 'meta' and 'content' folders have not all files. You have two options:
> 
> 1. You can download EUR version of Twilight Princess HD  'meta' and 'content' folders with Wii U USB Helper and add to your own folders rest of files.
> 2. You can use attached archive.
> 
> With best regards.
> 
> [Zelda.zip](https://github.com/RedDuckss/CemUI/files/4201315/Zelda.zip)

Markyza, It's not late. Thank you!

**Comment by ITGM13** [comment]
> > I got too the issue with Twilight Princess HD which had only this in its `meta`folder :
> > ![Capture](https://user-images.githubusercontent.com/9219052/60466489-15e49a80-9c54-11e9-9b70-4f2ebc4975df.PNG)
> > [meta.zip](https://github.com/RedDuckss/CemUI/files/3347310/meta.zip)
> 
> Maybe it's late, but your 'meta' and 'content' folders have not all files. You have two options:
> 
> 1. You can download EUR version of Twilight Princess HD  'meta' and 'content' folders with Wii U USB Helper and add to your own folders rest of files.
> 2. You can use attached archive.
> 
> With best regards.
> 
> [Zelda.zip](https://github.com/RedDuckss/CemUI/files/4201315/Zelda.zip)

Thanks I was searching for this problem and for the same game!

**Comment by LDCanetti** [comment]
does someone here has the meta folder of zelda the wind waker hd? it would be kind if you share it

**Comment by dictory99** [comment]
> does someone here has the meta folder of zelda the wind waker hd? it would be kind if you share it

try this one

[meta.zip](https://github.com/RedDuckss/CemUI/files/5823911/meta.zip)
