### ISSUE TITLE
FAST Racing NEO and New Super Luigi U. do not appear in the list

### ISSUE THREAD

**Issue by williansti** [RedDuckss/CemUI#55]
I have 18 games, however two games are not displayed in the launcher v2, they are, FAST Racing NEO and New Super Luigi U.

All games are in format rpl/rpx stored in the correct locations, in version 1 of the launcher are displayed correctly, already in v2 no.

![games](https://user-images.githubusercontent.com/10545674/30273383-25ef35de-96cf-11e7-8cfe-90d46bdabbe7.jpg)
![v1](https://user-images.githubusercontent.com/10545674/30273384-25eff78a-96cf-11e7-9dea-539f32690408.jpg)
![v2](https://user-images.githubusercontent.com/10545674/30273385-25f415ea-96cf-11e7-81ce-a5f29bb5ed49.jpg)

**Comment by mrjvs** [comment]
This has already been fixed in the latest dev version. Download and install the dev version or wait for the second alpha release for this fix. Thanks for the report anyway.
