### ISSUE TITLE
A bug happened

### ISSUE THREAD

**Issue by meowingtwurtle** [RedDuckss/CemUI#68]
- A detailed description of the bug
stuff happenes i nead halps pls giev meh teh help ya have
- Exact steps to reproduce
i did stuff and thingy happens
- A screenshot/video of the bug/error message
[![Screenshot of teh bug from Gyazo](https://gyazo.com/26b78bbcfa1c700f9b1f49c3d7052446/raw)](https://gyazo.com/26b78bbcfa1c700f9b1f49c3d7052446)
- List games affected (if applicable)
all  teh gaems
- If possible, a video or gif showing the exact steps to reproduce (There are many free video recorders out there. It doesn't matter how you record it, as long as it's recorded)

**Comment by MrIlliteracy** [comment]
o no, the bug. i fix

**Comment by meowingtwurtle** [comment]
ouch `invalid` is a bit harsh

**Comment by MrIlliteracy** [comment]
lol
