### ISSUE TITLE
[Suggestion] Change the icon because it's very ugly

### ISSUE THREAD

**Issue by ghost** [RedDuckss/CemUI#73]
Title

**Comment by RedDuckss** [comment]
Can you be more specific. There are 2 versions of the icon. There is the icon in the source code and the icon in the latest stable version, which are different from one another.

Also this is a matter of opinion and not a valid issue. Please mark suggestions as a suggestion, and if you want something that exists to be changed (like this) then please provide details on _why_ you want it to be changed and possibly some alternatives.

**Comment by ThePiranhaPlant** [comment]
This icon:
![ico](https://user-images.githubusercontent.com/26660840/32408392-4227ac0c-c197-11e7-8ed2-1d89d5e67891.png)

**Comment by RedDuckss** [comment]
And what exactly do you find ugly about it? Please refer to the latter half of my reply:
>Also this is a matter of opinion and not a valid issue. Please mark suggestions as a suggestion, and if you want something that exists to be changed (like this) then please provide details on _why_ you want it to be changed and possibly some alternatives.

**Comment by ThePiranhaPlant** [comment]
In my task bar it's ugly

**Comment by ThePiranhaPlant** [comment]
![image](https://user-images.githubusercontent.com/26660840/32408429-e7e1f378-c197-11e7-8452-064dbb6f726b.png)

**Comment by RedDuckss** [comment]
Are you running from source or from a built binary? The icon seems to look different if being ran from source than in a built binary.

**Comment by ThePiranhaPlant** [comment]
From the source code

**Comment by RedDuckss** [comment]
Try running from a built binary. You can build one using `build.js`

**Comment by ThePiranhaPlant** [comment]
![image](https://user-images.githubusercontent.com/26660840/32408439-284020c0-c198-11e7-9bb7-718a57643cad.png)

**Comment by RedDuckss** [comment]
https://i.imgur.com/hdVk2Fm.png
This is how it looks in a built binary. You can find a built binary here:
https://www.dropbox.com/s/78uu4uso0rn0vwi/CemUI%20final%207.exe?dl=0

**Comment by ThePiranhaPlant** [comment]
Sorry, but how do I use build. js to build? I'm a beginner

**Comment by mrjvs** [comment]
run it using `node build.js`

**Comment by RedDuckss** [comment]
Gonna close this since it isn't really a valid issue report, and I want to clean this section up
