### ISSUE TITLE
Unable to launch the game: After pressing play, another CEMUI window opens instead of the game window

### ISSUE THREAD

**Issue by James-Puli** [RedDuckss/CemUI#76]
I just installed CEMUI with the intent of playing Super Mario Maker. I followed the instructions briefed here (except I installed to an internal E: drive directory) :http://themindhero.com/smmg.html , and whenever I try to launch SMM, A small rectangular window opens, followed by another window of CEMUI opening. I have tried re-installing both CEMUI and SMM to no avail. 

Here is a link to a recording of me flailing around in an attempt to better outline the issue:
https://drive.google.com/open?id=1cE6xK3Qt_KUfyd9qDQQQgUpLx-sNeQ54

Honestly, this is my first time using the program, so the issue could very likely be down to human error.
Thanks so much for any help!

**Comment by mrjvs** [comment]
To me this seems like you have selected cemUi instead of cemu for the cemu instance. try going to the menu>settings>Cemu instances And Create a new instance and select the cemu this time. (Cemui and cemu are 2 different things) after you have done that remove the "default" cemu instance where you selected the wrong program.

**Comment by James-Puli** [comment]
You're Right! that does seem to be the issue, but I cannot "Remove" the 'Default' instance, whenever I press remove, it simply sits there and does nothing... I can add a new instance just fine however.
Thanks so much for the Hasty response, sorry that I couldn't reply as quickly.

**Comment by James-Puli** [comment]
No worries, I just manually deleted it by digging through some of the program files. Thanks so much for the help!

**Comment by mrjvs** [comment]
Awesome, I'm glad it's resolved.

**Comment by RedDuckss** [comment]
Just to note, do not remove the `Default` instance. If you _need_ to change it, then just change the path. CemUI references the `Default` instance internally in several places and will break if it cannot find `Default`. That is why you cannot remove it from within the UI.
