### ISSUE TITLE
not creating desktop shortcut of games on desktop

### ISSUE THREAD

**Issue by RazorStrike** [RedDuckss/CemUI#77]
I found out it's creating the desktop shortcut at C:\Users\User\Desktop and not at the \desktop.

**Comment by RedDuckss** [comment]
Those two paths are the same as far as the (Windows) OS is concerned, they both lead to the same directory. Closing issue.

**Comment by dnfanjos** [comment]
actually if you have onedrive your desktop turns into onedrive folder´s desktop

**Comment by dnfanjos** [comment]
so i had to go to that directory to get the shortcuts

(can u make it so we can customize the shortcuts location?)
