### ISSUE TITLE
AM & PM mix up

### ISSUE THREAD

**Issue by Nybbit** [RedDuckss/CemUI#80]
When it's 12 PM, it says that it is 12 AM

## Actual time
![Actual Time](https://i.imgur.com/zZqY8ro.png)
## Time according to CemUI
![CemUI Time](https://i.imgur.com/sAazIKu.png)

literally unusuable

**Comment by RedDuckss** [comment]
tagging @mrjvs since he made this clock

**Comment by mrjvs** [comment]
issue fixed in the latest commit, newest update will include this fix.
