### ISSUE TITLE
Unwanted desktop files created

### ISSUE THREAD

**Issue by Landerson89** [RedDuckss/CemUI#83]
I'm having an issue with creating the desktop shortcut, using breath of the wild as my example. I get the the icon to appear on my desktop but when i click it, it creates a log file then a shaders folder etc right there on the desktop, i like having the Zelda icon on my desktop but the additional stuff is doing my head in!

Help

**Comment by RedDuckss** [comment]
Cannot replicate issue. Please follow the issue reporting template to provide more information about your specific environment so that we can better help you.

**Comment by RedDuckss** [comment]
Over two weeks of inactivity on this issue from the issuer, and I also still cannot recreate this issue on any build of CemUI. As such I will be closing this issue report until further details are given
