### ISSUE TITLE
Unable to remove default game directory

### ISSUE THREAD

**Issue by jazir5** [RedDuckss/CemUI#84]
Latest version of CEMUI in releases at time of this posting
- 

- in the settings panel of CEMUI in the game folder path section, unable to remove default directory

- Go to the panel for the directory and press remove for the default, nothing happens. Non-default directories are removable

**Comment by RedDuckss** [comment]
Do you have only one game folder saved? If you have multiple then you should be able to remove any of them. CemUI does not track a "default" for the game folders. CemUI will prevent you from removing the game folder if there is only one saved, as it requires at least one to function, but having multiple should allow you to remove the unwanted one.

**Comment by jazir5** [comment]
Ok gotcha. Yeah it was unremovable when only one was listed. Maybe put an
error message saying that?

**Comment by jazir5** [comment]
Thanks :)

**Comment by RedDuckss** [comment]
Will be in the next release
