### ISSUE TITLE
Can't open CemUI - "A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by GorawPT** [RedDuckss/CemUI#97]
I'm getting an issue while trying to open the program, i saw that it started to happen after i updated the java last week, but i don't know if this is the issue.

- When i open the program it get stucks on the loading screen and the [this message](https://i.imgur.com/EoXbRc6.jpg) appears and nothing happens;
- Already tried to reinstall it and to downgrade, the downgrade worked but is not the best soluiton.

GIF of the problem: https://media.giphy.com/media/5hvIgGgB4xCexd80Zq/giphy.gif

**Comment by yoyoyogurt** [comment]
i have the same problem this is the error message I get:
![afbeelding](https://user-images.githubusercontent.com/39498212/40322626-3ba37892-5d33-11e8-86a9-bfefdb6296b8.png)

**Comment by RedDuckss** [comment]
Issue's have been fixed, it was a server side issue that I didn't have time to resolve until now. The proper API version is back online (I still have no idea why it started using v1 again). All should be well.
