### ISSUE TITLE
downloads page blank

### ISSUE THREAD

**Issue by Tyfyter** [RedDuckss/CemUI#98]
the downloads page is not loading anything on windows 7, either it is bugged and not loading, or it just takes an extremely long time to load.
![ezgif-2-05e7eb7b7e](https://user-images.githubusercontent.com/25260026/36572204-676bdac0-1808-11e8-8db8-f42e6bcc5a6c.gif)

**Comment by bobojo** [comment]
I'm having the same problem on a Bootcamp partition of my MacBook Pro using Windows 10. Is my machine just incompatible maybe?

**Comment by jdroo** [comment]
Same issue, have all the stuff it needs, wont populate the downloads page.

**Comment by tr3iscool** [comment]
Same here please fix or help.

**Comment by Rigormortus** [comment]
Same issue here, tried reinstalling multiple times, still no search results.

**Comment by RedDuckss** [comment]
Issue's have been fixed, it was a server side issue that I didn't have time to resolve until now. The proper API version is back online (I still have no idea why it started using v1 again). All should be well.
