### ISSUE TITLE
CEMUI can't find Mario Maker when I search for it

### ISSUE THREAD

**Issue by Joshuabump** [RedDuckss/CemUI#99]
I was trying to download Mario Maker, I clicked on MENU, clicked DOWNLOAD GAMES, typed in Super Mario Maker, I hit enter and nothing happened
![bandicam 2018-02-25 13-16-49-551](https://user-images.githubusercontent.com/24300971/36644854-2dcf29c0-1a2e-11e8-86d4-23328f6bc7a6.png)

**Comment by Crinfarr** [comment]
I think it's an issue with the downloads center in particular, given that it supposedly searches while you type, even though no network activity is shown while searching.  Check your metadata and config files, there might be help there somewhere.

**Comment by RedDuckss** [comment]
Issue's have been fixed, it was a server side issue that I didn't have time to resolve until now. The proper API version is back online (I still have no idea why it started using v1 again). All should be well.
